### ISSUE TITLE
HTML markup in title of results

### ISSUE THREAD

**Issue by srcthomas** [WebberZone/better-search#22]
Search results showing parts of title tag with search term contained in them.

![html_markup_in_search_result](https://cloud.githubusercontent.com/assets/9561656/22811066/827ea076-efa1-11e6-92a4-41d69a2edcd6.jpg)

**Comment by ajaydsouza** [comment]
Hi, 

I've done some testing on this. While I'm not sure which theme you are using, I suspect the reason you have this error is because the title attribute is using `get_the_title` which in turn using the `the_title` filter that is used by the plugin to highlight.

I tested this with TwentySeventeen theme 
`			the_title( sprintf( '<h2 class="entry-title"><a href="%s" rel="bookmark" title="%s">', esc_url( get_permalink() ), esc_attr( get_the_title() ) ), '</a></h2>' );
`

The only option in this set up is to either disable the highlighting or alternatively, add `remove_filter( 'the_title', 'bsearch_content', 99 );` to your theme's functions.php file which will remove the highlighting from the titles but keep the content.

Of course an alternative is to remove the title attribute from being displayed on the search pages/post listings.
